const buildEnv = () =>{

    cy.server()
    cy.route({
        method: 'POST',
        url: '/signin',
        response: { id: 1000, nome: 'usuario falso', token: 'String token falso'    }
        }).as('signin')

    cy.route({
        method: 'GET',
        url: '/saldo',
        response:[{  "conta_id": 666, "conta": "Carteira", "saldo": "1000" },
                {"conta_id": 999, "conta": "Banco","saldo": "1000000000000000000"   }
        ]}).as('saldo')

    cy.route({
        method:'GET',
        url: '/contas',
        response:[{
                "conta": "Conta para movimentacoes",
                "id": 1929928,
                "descricao": "Movimentacao para exclusao",
                "envolvido": "AAA",
                "observacao": null,
                "tipo": "DESP",
                "data_transacao": "2024-03-10T03:00:00.000Z",
                "data_pagamento": "2024-03-10T03:00:00.000Z",
                "valor": "-1500.00",
                "status": true,
                "conta_id": 2058645,
                "usuario_id": 47637,
                "transferencia_id": null,
                "parcelamento_id": null },
            { "conta": "Conta com movimentacao",
                "id": 1929929,
                "descricao": "Movimentacao de conta",
                "envolvido": "BBB",
                "observacao": null,
                "tipo": "DESP",
                "data_transacao": "2024-03-10T03:00:00.000Z",
                "data_pagamento": "2024-03-10T03:00:00.000Z",
                "valor": "-1500.00",
                "status": true,
                "conta_id": 2058646,
                "usuario_id": 47637,
                "transferencia_id": null,
                "parcelamento_id": null},
            {"conta": "Conta para saldo",
                "id": 1929930,
                "descricao": "Movimentacao 1, calculo saldo",
                "envolvido": "CCC",
                "observacao": null,
                "tipo": "REC",
                "data_transacao": "2024-03-10T03:00:00.000Z",
                "data_pagamento": "2024-03-10T03:00:00.000Z",
                "valor": "3500.00",
                "status": false,
                "conta_id": 2058647,
                "usuario_id": 47637,
                "transferencia_id": null,
                "parcelamento_id": null},
            {"conta": "Conta para saldo",
                "id": 1929931,
                "descricao": "Movimentacao 2, calculo saldo",
                "envolvido": "DDD",
                "observacao": null,
                "tipo": "DESP",
                "data_transacao": "2024-03-10T03:00:00.000Z",
                "data_pagamento": "2024-03-10T03:00:00.000Z",
                "valor": "-1000.00",
                "status": true,
                "conta_id": 2058647,
                "usuario_id": 47637,
                "transferencia_id": null,
                "parcelamento_id": null},
            {"conta": "Conta para saldo",
                "id": 1929932,
                "descricao": "Movimentacao 3, calculo saldo",
                "envolvido": "EEE",
                "observacao": null,
                "tipo": "REC",
                "data_transacao": "2024-03-10T03:00:00.000Z",
                "data_pagamento": "2024-03-10T03:00:00.000Z",
                "valor": "1534.00",
                "status": true,
                "conta_id": 2058647,
                "usuario_id": 47637,
                "transferencia_id": null,
                "parcelamento_id": null},
            {"conta": "Conta para extrato",
                "id": 1929933,
                "descricao": "Movimentacao para extrato",
                "envolvido": "FFF",
                "observacao": null,
                "tipo": "DESP",
                "data_transacao": "2024-03-10T03:00:00.000Z",
                "data_pagamento": "2024-03-10T03:00:00.000Z",
                "valor": "-220.00",
                "status": true,
                "conta_id": 2058648,
                "usuario_id": 47637,
                "transferencia_id": null,
                "parcelamento_id": null }]
        }).as('listar conta');
}

export default buildEnv
